name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: ./start-mini-obs.sh

    - run: yarn install

    - run: |
        yarn run test
        yarn run coverage
      env:
        HAVE_MINI_OBS: 1

    - name: cleanup
      run: |
        pushd open-build-service
        docker-compose stop
        popd

  lint:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - run: yarn install
    - run: yarn run lint

  documentation:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - run: yarn install
    - run: yarn run documentation

  add_license:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: |
        export GOPATH="$(pwd)/golang"
        mkdir -p ${GOPATH}
        go get -u github.com/google/addlicense
        ${GOPATH}/bin/addlicense -c "SUSE LLC" -l mit $(find test/ src/ -name '*\.ts')
        git diff --exit-code
